### PR TITLE
Just easier manual for linux machines.

### PR DESCRIPTION
**Pull request by RexAckermann**

### CODE REVIEW

**Comment by RaSan147** [comment]
I'll test it with wsl asap, looks good.

**Comment by RexAckermann** [comment]
Oh ,I tested this one.So ,I think it will work just fine.

**Comment by RaSan147** [comment]
Yeah working great. But 7z plugin is somehow messing up(sudo apt not found etc), I'll push a big change in a day or 2 and merge your commit.

**Comment by RaSan147** [comment]
used `curl` instead of `wget` since wget don't replace old file

**Pull request merged**
